import Head from 'next/head'
import Image from 'next/image'
import { Geist, Geist_Mono } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'

import MyNav from '@/components/MyNav'
import Login from '@/components/Login'
import { useAppContext } from '../context/Context'
import ProductList from '@/components/ProductList'
import Cart from '@/components/Cart'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function Home() {
  const { user, logoutUser, cart } = useAppContext()

  return (
    <>
      {/* <Provider store={store}> */}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {/* <MyNav /> */}
        {!user ? (
          <Login />
        ) : (
          <div>
            <ProductList />
            <Cart />
          </div>
        )}
      </div>
      {/* </Provider> */}
    </>
  )
}
